CREATE EXTERNAL TABLE securityxceftest (
    dates STRING,  
    time string,  
    sev string,  
    act string,  
    app string,  
    cat string,  
    cnt string,  
    dhost string,  
    dpid string,  
    dmac string,  
    dntdom string,  
    dpriv string,  
    dproc string,  
    dpt string,  
    dst string,  
    duid string,  
    duser string,  
    dvc string,  
    dvchost string,  
    dvcpid string,  
    ends string,  
    fname string,  
    fsize int,  
    ins string,  
    msg string,  
    outcome string,  
    outs string,  
    proto string,  
    request string,  
    rt string,  
    shost string,  
    smac string,  
    sntdom string,  
    spid string,  
    sproc string,  
    spt string,  
    spriv string,  
    src string,  
    start string,  
    suid string,  
    suser string,  
    cs1 string,  
    cs2 string,  
    cs3 string,  
    cs4 string
) 
PARTITIONED BY (datehourminute INT)
row format delimited fields
terminated by '09' lines terminated by '10'
location '/securityx/flume/testout-table'

